### ISSUE TITLE
file not found

### ISSUE THREAD

**Issue by Mark-papi** [nagadit/DeepFaceLab_Linux#16] opened 2020-11-12 10:15 UTC
hello!
when running this sh 2_extract_PNG_from_video_data_src.sh
i get this error 2_extract_PNG_from_video_data_src.sh: line 2: source: env.sh: file not found

**Comment by nagadit** [comment] 2020-11-12 10:20
Scripts must be run from the scripts directory and not from the root
@Mark-papi

**Comment by Mark-papi** [comment] 2020-11-12 10:23
@nagadit 
hi, thanks for the fast reply,
i am on the (deepfacelab) [sollekram@sollekrampc scripts]$
directory when running it

**Comment by nagadit** [comment] 2020-11-12 10:24
Show me your 
```
ls
```

**Comment by Mark-papi** [comment] 2020-11-12 10:28
![Screenshot_2020-11-12_14-28-09](https://user-images.githubusercontent.com/12816482/98928590-9e2ead00-24e2-11eb-9e86-83b8e6d434e0.png)

**Comment by nagadit** [comment] 2020-11-12 10:32
on other scripts the same error?

**Comment by nagadit** [comment] 2020-11-12 10:34
everything works well for me

**Comment by Mark-papi** [comment] 2020-11-12 10:35
![Screenshot_2020-11-12_14-35-00](https://user-images.githubusercontent.com/12816482/98929221-8277d680-24e3-11eb-91d1-ee69e4dee8b6.png)

**Comment by Mark-papi** [comment] 2020-11-12 10:36
the only script that dont prompt me error is the env.sh

**Comment by nagadit** [comment] 2020-11-12 10:38
Try run scripts with `bash` 
like 
`bash 2_extract_PNG_from_video_data_src.sh`

**Comment by Mark-papi** [comment] 2020-11-12 10:40
thankssss, with bash its seems to running, but i get an other error saying 
python3.6: can't open file './DeepFaceLab/main.py': [Errno 2] No such file or directory

**Comment by nagadit** [comment] 2020-11-12 10:42
> thankssss, with bash its seems to running, but i get an other error saying
> python3.6: can't open file './DeepFaceLab/main.py': [Errno 2] No such file or directory

you need to complete all actions [here](https://github.com/nagadit/DeepFaceLab_Linux/blob/master/README.md#3-install-deepfacelab)

**Comment by Mark-papi** [comment] 2020-11-12 10:43
opsss probably missed that one git clone https://github.com/iperov/DeepFaceLab.git
lol 
Thank you so much!!!

**Comment by nagadit** [comment] 2020-11-12 10:44
Your fake "Mac os: confused me. Your problem is described [here](https://stackoverflow.com/questions/13702425/source-command-not-found-in-sh-shell)

**Comment by Mark-papi** [comment] 2020-11-12 10:45
hahahah yea its a fake interface to look like Mac os

**Comment by nagadit** [comment] 2020-11-12 10:46
If the problem is solved and there are no more questions, you can close this issue

**Comment by Mark-papi** [comment] 2020-11-12 10:48
Perfect thank you again!!!

**Comment by Mark-papi** [comment] 2020-11-12 15:56
sorry if im getting really annoying :p 
i managed to get it work but when i try to export faces i get this error
`bash 4.2_data_src_util_faceset_enhance.sh

Choose one or several GPU idxs (separated by comma).

[CPU] : CPU
  [0] : GeForce GTX 1660 SUPER

[0] Which GPU indexes to choose? : 0
0

Enhancing faceset in data_src/aligned
Processing to data_src/aligned_enhanced
Error while subprocess initialization: Traceback (most recent call last):
  File "/home/sollekram/.local/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/sollekram/.local/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/sollekram/.local/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.10.0: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sollekram/DeepFaceLab/DeepFaceLab/core/joblib/SubprocessorBase.py", line 62, in _subprocess_run
    self.on_initialize(client_dict)
  File "/home/sollekram/DeepFaceLab/DeepFaceLab/mainscripts/FacesetEnhancer.py", line 89, in on_initialize
    nn.initialize (device_config)
  File "/home/sollekram/DeepFaceLab/DeepFaceLab/core/leras/nn.py", line 80, in initialize
    import tensorflow as tf
  File "/home/sollekram/.local/lib/python3.6/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/home/sollekram/.local/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/sollekram/.local/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/sollekram/.local/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/sollekram/.local/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/sollekram/.local/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.10.0: cannot open shared object file: No such file or directory


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

Traceback (most recent call last):
  File "./DeepFaceLab/main.py", line 324, in <module>
    arguments.func(arguments)
  File "./DeepFaceLab/main.py", line 246, in process_faceset_enhancer
    force_gpu_idxs=arguments.force_gpu_idxs
  File "/home/sollekram/DeepFaceLab/DeepFaceLab/mainscripts/FacesetEnhancer.py", line 143, in process_folder
    result = FacesetEnhancerSubprocessor ( image_paths, output_dirpath, device_config=device_config).run()
  File "/home/sollekram/DeepFaceLab/DeepFaceLab/core/joblib/SubprocessorBase.py", line 210, in run
    raise Exception ( "Unable to start subprocesses." )
Exception: Unable to start subprocesses.
`
something with cuda i presume ? 
i try to install from arch linux aur the cuda latest version

**Comment by nagadit** [comment] 2020-11-12 16:07
I will not help you, the problem has nothing to do with dfl, but only with your system

**Closed** 2020-11-12 16:13 UTC
